"""End-to-end contract validation: schema, parsing, and server round-trip.

The server round-trip tests mock out the LLM4Decompile models so they stay
fast unit tests (no GPU / multi-GB model load).
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

import torch
from fastapi.testclient import TestClient

import windy_gclsd.server as server_mod
from windy_gclsd.contract import GclsdInput
from windy_gclsd.server import app, build_asm_text

CONTRACT_ROOT = Path(__file__).parent.parent / "contract"
FIXTURES_ROOT = Path(__file__).parent / "fixtures"


def _stub_model(slot: str = "quality") -> None:
    """Pre-populate the model registry with sentinel values so loading is skipped."""
    server_mod._models[slot] = server_mod.LoadedModel(
        name=f"stub-{slot}",
        model=object(),
        tokenizer=object(),
        device=torch.device("cpu"),
        param_count=0,
    )


def _stub_all() -> None:
    _stub_model("quality")
    _stub_model("fast")


def test_schema_emitted() -> None:
    schema_path = CONTRACT_ROOT / "gclsd_input.schema.json"
    assert schema_path.exists(), "schema must be generated by the Rust host"
    schema = json.loads(schema_path.read_text())
    assert schema["title"] == "GclsdInput"
    assert "GclsdEdgeKind" not in schema["$defs"]["GclsdEdge"]["properties"]["kind"]


def test_parses_authored_sample() -> None:
    fixture = FIXTURES_ROOT / "authored_smoke.gclsd.jsonl"
    assert fixture.exists()
    with fixture.open() as f:
        first = json.loads(next(f))
    parsed = GclsdInput.model_validate(first)
    assert parsed.bitness == 64
    assert parsed.instructions
    assert parsed.blocks


def test_build_asm_text_format() -> None:
    """build_asm_text renders AT&T-syntax asm via capstone re-disassembly."""
    fixture = FIXTURES_ROOT / "authored_smoke.gclsd.jsonl"
    assert fixture.exists()
    with fixture.open() as f:
        payload = json.loads(next(f))
    parsed = GclsdInput.model_validate(payload)

    text = build_asm_text(parsed)
    lines = text.split("\n")
    assert lines[0] == f"{parsed.name}:"
    assert len(lines) > 1
    for line in lines[1:]:
        assert len(line) > 0, "empty asm line"


def test_build_asm_text_empty() -> None:
    g = GclsdInput(
        name="empty", entry_va=0, image_base=0, bitness=64,
        params=[], instructions=[], blocks=[],
        xrefs_in=[], xrefs_out=[],
    )
    assert build_asm_text(g) == "empty:\n"


def test_server_round_trip_quality() -> None:
    """The /decompile endpoint pipes asm text -> _generate -> pseudocode (quality)."""
    _stub_model("quality")
    fixture = FIXTURES_ROOT / "authored_smoke.gclsd.jsonl"
    with fixture.open() as f:
        payload = json.loads(next(f))

    fake_output = "int main() { return 0; }"
    with patch.object(server_mod, "_generate", return_value=fake_output) as mock_gen:
        client = TestClient(app)
        response = client.post("/decompile", json=payload)
        assert response.status_code == 200
        body = response.json()
        assert body["pseudocode"] == fake_output
        mock_gen.assert_called_once()
        # First arg is the LoadedModel, second is the asm text.
        asm_arg = mock_gen.call_args[0][1]
        assert asm_arg.startswith(payload["name"] + ":")


def test_server_round_trip_fast_model() -> None:
    """The ?model=fast query routes to the fast model slot."""
    _stub_all()
    fixture = FIXTURES_ROOT / "authored_smoke.gclsd.jsonl"
    with fixture.open() as f:
        payload = json.loads(next(f))

    with patch.object(server_mod, "_generate", return_value="void f() {}") as mock_gen:
        client = TestClient(app)
        response = client.post("/decompile", json=payload, params={"model": "fast"})
        assert response.status_code == 200
        # _generate was called with the *fast* LoadedModel.
        lm_arg = mock_gen.call_args[0][0]
        assert lm_arg.name == "stub-fast"


def test_health_endpoint() -> None:
    _stub_all()
    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code == 200
    body = response.json()
    assert body["status"] == "ok"
    assert "models" in body
    assert body["models"]["quality"] is not None


def test_empty_instructions_returns_comment() -> None:
    _stub_all()
    payload = {
        "name": "stub_fn", "entry_va": 0, "image_base": 0, "bitness": 64,
        "params": [], "instructions": [], "blocks": [],
        "xrefs_in": [], "xrefs_out": [],
    }
    client = TestClient(app)
    response = client.post("/decompile", json=payload)
    assert response.status_code == 200
    body = response.json()
    assert body["pseudocode"].startswith("// no instructions")


def test_unknown_model_returns_error() -> None:
    _stub_all()
    payload = {
        "name": "stub_fn", "entry_va": 0, "image_base": 0, "bitness": 64,
        "params": [], "instructions": [{"ip":0,"bytes_hex":"90","mnemonic":"nop",
        "operands":"","flow":"Next","class":"Logic","reads":[],"writes":[],"mem_refs":[]}],
        "blocks": [{"entry_va":0,"instr_ips":[0],"successors":[]}],
        "xrefs_in": [], "xrefs_out": [],
    }
    client = TestClient(app)
    response = client.post("/decompile", json=payload, params={"model": "bogus"})
    assert response.status_code == 422 or response.status_code == 400
